#!/bin/bash

# Written by Jake Tesler (8/15/17)
# Version 2 (5/24/19)

MONITOR=false
RESTART=false
STOP=false
START=false
SERVICE=""
SHOULD_EXIT=false

while getopts ":hm:r:s:S:i:" arg; do

	if test "$OPTARG" = "$(eval echo '$'$((OPTIND - 1)))"; then
        OPTIND=$((OPTIND - 1))
    fi

	case $arg in
		m)
			MONITOR=true
			SERVICE="$OPTARG"
			;;
		r)
			RESTART=true
			SERVICE="$OPTARG"
			;;
		s)
			START=true
			SERVICE="$OPTARG"
			;;
		S)
			STOP=true
			SERVICE="$OPTARG"
			;;
		i)
			STATUS=true
			SERVICE="$OPTARG"
			;;
		h)
			echo "Usage: srv [-m] [-i] [-r|-s|-S] service"
			exit 0
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			SHOULD_EXIT=true
			;;
	esac
done

if [ "$SHOULD_EXIT" = true ]; then exit 0; fi

if test "$SERVICE" = "$(eval echo '$'$((OPTIND - 1)))"; then
    echo "Please provide a service name."
    exit 0
fi

if [ "$RESTART" = true ]; then
	START=false
	STOP=false
	echo "Restarting $SERVICE..."
	sudo systemctl restart $SERVICE
fi

if [ "$STOP" = true ]; then
	echo "Stopping $SERVICE..."
	sudo systemctl stop $SERVICE
fi

if [ "$START" = true ]; then
	echo "Starting $SERVICE..."
	sudo systemctl start $SERVICE
fi

if [ "$STATUS" = true ]; then
	# echo "Gathering status for $SERVICE."
	sudo systemctl status $SERVICE
fi

if [ "$MONITOR" = true ]; then
	# echo "Monitoring $SERVICE."
	sudo journalctl -n 100 -f -u $SERVICE
fi



# function srv_cmd()
# {
# 	while getopts hm:r:s:S:i: arg; do
# 		case $arg in
# 			m)
# 				sudo journalctl -n 75 -f -u $OPTARG
# 				;;
# 			r)
# 				sudo systemctl restart $OPTARG
# 				;;
# 			s)
# 				sudo systemctl start $OPTARG
# 				;;
# 			S)
# 				sudo systemctl stop $OPTARG
# 				;;
# 			i)
# 				sudo systemctl status $OPTARG
# 				;;
# 			\?)
# 				echo "Invalid option: -$OPTARG" >&2
# 				;;
# 		esac
# 	done
# }
#
# function _completion_()
# {
# 	SERVICES=$(systemctl list-unit-files -a --no-pager --no-legend | awk '{print $1}')
# 	COMPREPLY+=($SERVICES)
# }
#
# complete -F _completion_ srv_cmd
